### ISSUE TITLE
make constant out of URL

### ISSUE THREAD

**Issue by discospiff** [mikeal200/Party-Player#19]
I see "api.spotify.com" in several places throughout the code.  Consider making a constant of just that root URL, so that you don't have to copy it everywhere.  This will make maintenance much easier, if that URL ever changes.

https://github.com/mikeal200/Party-Player/blob/b4b8a358e40b09a522d1cd3ce4e4350ba9cfc445/app/src/main/java/com/example/party_player/Playlist.kt#L15

**Comment by mikeal200** [comment]
i made a constant in the main now thank you for the advice i was actually able to take https://api.spotify.com/v1/ and make that a constant.
